{
  VoltTable[] results;
  boolean threwException;
  VoltDB.instance().getHostMessenger().getZK().delete(VoltZK.restoreMarker,-1);
  VoltDB.instance().getHostMessenger().getZK().delete(VoltZK.perPartitionTxnIds,-1);
  threwException=false;
  try {
    JSONObject jsObj=new JSONObject();
    jsObj.put(SnapshotRestore.JSON_NONCE,TESTNONCE);
    jsObj.put(SnapshotRestore.JSON_PATH,TMPDIR);
    jsObj.put(SnapshotRestore.JSON_DUPLICATES_PATH,TMPDIR);
    results=client.callProcedure("@SnapshotRestore",jsObj.toString()).getResults();
    while (results[0].advanceRow()) {
      if (results[0].getString("RESULT").equals("FAILURE")) {
        fail(results[0].getString("ERR_MSG"));
      }
    }
  }
 catch (  Exception ex) {
    threwException=true;
  }
  assertFalse(threwException);
}
