{
  if (!isDone()) {
    try {
      set(callable.call());
    }
 catch (    Throwable t) {
      setException(t);
    }
  }
}
