{
  logHardStop("Unexpected exception",e);
  stopTheWorld();
}
