{
  try {
    assertSame(x,y);
  }
 catch (  AssertionFailedError t) {
    threadRecordFailure(t);
    throw t;
  }
}
