{
  try {
    runBenchmark();
  }
 catch (  Exception e) {
    return;
  }
}
