@patch('jenkins.urlopen')
def test_response_404(self, jenkins_mock):
    jenkins_mock.side_effect = jenkins.HTTPError(self.make_url('job/TestJob'), code=404, msg='basic auth failed', hdrs=[], fp=None)
    request = jenkins.Request(self.make_url('job/TestJob'))
    with self.assertRaises(jenkins.NotFoundException) as context_manager:
        self.j.jenkins_open(request, add_crumb=False)
    self.assertEqual(str(context_manager.exception), 'Requested item could not be found')
    self.assertEqual(jenkins_mock.call_args[0][0].get_full_url(), self.make_url('job/TestJob'))
    self._check_requests(jenkins_mock.call_args_list)
