@patch.object(jenkins.Jenkins, 'jenkins_open')
def test_already_exists(self, jenkins_mock):
    jenkins_mock.side_effect = [json.dumps({'name': 'TestJob', }), None]
    with self.assertRaises(jenkins.JenkinsException) as context_manager:
        self.j.create_job(u'TestJob', self.config_xml)
    self.assertEqual(jenkins_mock.call_args_list[0][0][0].get_full_url(), self.make_url('job/TestJob/api/json?tree=name'))
    self.assertEqual(str(context_manager.exception), 'job[TestJob] already exists')
    self._check_requests(jenkins_mock.call_args_list)
