{
  for (  ExecutionSiteRunner r : m_runners) {
    r.m_shouldStartRunning.countDown();
  }
  if (m_restoreAgent != null) {
    m_restoreAgent.restore();
  }
 else {
    onRestoreCompletion(Long.MIN_VALUE);
  }
  Thread.currentThread().setName("ExecutionSiteAndVoltDB");
  m_isRunning=true;
  try {
    m_currentThreadSite.run();
  }
 catch (  Throwable t) {
    String errmsg="ExecutionSite: " + org.voltcore.utils.CoreUtils.hsIdToString(m_currentThreadSite.m_siteId) + " encountered an "+ "unexpected error and will die, taking this VoltDB node down.";
    hostLog.error(errmsg);
    t.printStackTrace();
    VoltDB.crashLocalVoltDB(errmsg,true,t);
  }
}
