{
  if (!isIV2Enabled()) {
    for (    ExecutionSiteRunner r : m_runners) {
      r.m_shouldStartRunning.countDown();
    }
  }
  if (m_joiner != null) {
    try {
      if (!m_joiner.startJoin(m_clientInterfaces.get(0),m_myHostId)) {
        VoltDB.crashLocalVoltDB("Failed to join the cluster",true,null);
      }
    }
 catch (    Exception e) {
      VoltDB.crashLocalVoltDB("Failed to join the cluster",true,e);
    }
  }
  if (m_restoreAgent != null) {
    m_restoreAgent.restore();
  }
 else {
    onRestoreCompletion(Long.MIN_VALUE,m_iv2InitiatorStartingTxnIds);
  }
  if (m_rejoinCoordinator != null) {
    m_rejoinCoordinator.startRejoin();
  }
  Thread.currentThread().setName("ExecutionSiteAndVoltDB");
  m_isRunning=true;
  try {
    if (!isIV2Enabled()) {
      m_currentThreadSite.run();
    }
 else {
      while (m_isRunning) {
        Thread.sleep(3000);
      }
    }
  }
 catch (  Throwable thrown) {
    String errmsg=" encountered an unexpected error and will die, taking this VoltDB node down.";
    hostLog.error(errmsg);
    hostLog.fatal("Stack trace of thrown exception: " + thrown.toString());
    for (    StackTraceElement ste : thrown.getStackTrace()) {
      hostLog.fatal(ste.toString());
    }
    VoltDB.crashLocalVoltDB(errmsg,true,thrown);
  }
}
