@patch.object(jenkins.Jenkins, 'jenkins_open')
def test_unexpected_view_name(self, jenkins_mock):
    view_name_to_return = {u'name': 'not the right name', }
    jenkins_mock.return_value = json.dumps(view_name_to_return)
    with self.assertRaises(jenkins.JenkinsException) as context_manager:
        self.j.get_view_name(u'TestView')
    self.assertEqual(jenkins_mock.call_args_list[0][0][0].get_full_url(), self.make_url('view/TestView/api/json?tree=name'))
    self.assertEqual(str(context_manager.exception), 'Jenkins returned an unexpected view name {0} (expected: {1})'.format(view_name_to_return['name'], 'TestView'))
    self._check_requests(jenkins_mock.call_args_list)
